name: Android Emulator
on:
  pull_request:
    branches: [ master ]

  push:
    branches: [ master ]

  workflow_dispatch:

jobs:

  emulator:
    name: Start Emulator
    runs-on: macos-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Google services configuration
        env:
          GOOGLE_SERVICE: ${{ secrets.GOOGLE_SERVICE }}
        run: |
          echo "$GOOGLE_SERVICE" >> app/google-services.json

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          script: ./gradlew build connectedCheck --full-stacktrace
