name: Android Emulator
on:
  pull_request:
    branches: [ master ]
    
  push: 
    branches: [ master ]
    
  workflow_dispatch:

jobs:

  emulator:
    name: Start Emulator
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Google services configuration
        run: |
          echo "${{ secrets.GOOGLE_SERVICE }}" >> app/google-services.json

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck
